### ISSUE TITLE
לא ברור למה זה נכון

### ISSUE THREAD

**Issue by erelsgl** [ShmuelLa/research-algorithms#1]
https://github.com/ShmuelLa/research-algorithms/blob/ad6899e371956a50843372dabd286891efa8e66c/HW4/hw4_tests.py#L79
הרי הדגל אומר לו לא להחזיר את המסלול

**Comment by ShmuelLa** [comment]
טופל.
FW עכשיו מחזיר או את האורך מסלול או את המסלול כולו לפי דגל.

מתחיל טסטים.

תודה!
